main: com.github.koxsosen.bukkit.BukkitPluginLoader
name: SimpleVoiceBans
api-version: 1.13
version: 1.4-SNAPSHOT
softdepend:
  - LibertyBans
depend: [ voicechat ]
author: KoxSosen
permissions:
  simplevoicebans.actionbar:
    description: Sends an action bar if the player has the permission.
    default: false
